#pragma once

#include <array>
#include <cstdint>
#include <string>

namespace TerminalGames
{
    /**
     * @brief Some C++ functions are not supported by some compilers (usually because the function call fails with GNU 12.2.0
     * within the CI workflow). The following functions are crudely implemented below for this project's specific use case.
     */
    // Should work for all std containers
    template<typename T, typename U>
    static T ImplementStdRangesFind(const T& p_begin, const T& p_end, const U& p_value) // NOLINT(bugprone-easily-swappable-parameters)
    {
        for (T i = p_begin; i < p_end; i++)
        {
            if (*i == p_value)
            {
                return i;
            }
        }

        return p_end;
    }

    // Should work for all std containers
    template<typename T, typename U>
    static int32_t ImplementStdCount(const T& p_begin, const T& p_end, const U& p_value) // NOLINT(bugprone-easily-swappable-parameters)
    {
        int32_t count = 0;

        for (T i = p_begin; i < p_end; i++)
        {
            if (*i == p_value)
            {
                ++count;
            }
        }

        return count;
    }

    // Only works for single instance of {} in p_stringToFormat
    static std::string ImplementStdFormat(const std::string& p_stringToFormat, const uint32_t& p_varToInsert)
    {
        const std::string FORMAT_IDENTIFIER = "{}";
        const std::string BEFORE_STRING = p_stringToFormat.substr(0, p_stringToFormat.find(FORMAT_IDENTIFIER));
        const std::string AFTER_STRING = p_stringToFormat.substr(p_stringToFormat.find(FORMAT_IDENTIFIER) + FORMAT_IDENTIFIER.size(), p_stringToFormat.size() - p_stringToFormat.find("{}"));

        return BEFORE_STRING + std::to_string(p_varToInsert) + AFTER_STRING;
    }

    /**
     * @brief MainMenu
     */
    static constexpr uint32_t G_MAIN_MENU_DISPLAY_WIDTH = 30;
    static constexpr uint32_t G_MAIN_MENU_DISPLAY_HEIGHT = 13;

    /**
     * @brief Tic Tac Toe
     */
    static constexpr uint32_t G_TICTACTOE_DISPLAY_WIDTH = 53;
    static constexpr uint32_t G_TICTACTOE_DISPLAY_HEIGHT = 19;
    static constexpr uint32_t G_TICTACTOE_BOARD_WIDTH = 3;
    static constexpr uint32_t G_TICTACTOE_BOARD_HEIGHT = 3;
    static constexpr uint32_t G_TICTACTOE_GRID_ELEMENT_WIDTH = 4;
    static constexpr uint32_t G_TICTACTOE_GRID_ELEMENT_HEIGHT = 2;
    static constexpr uint32_t G_TICTACTOE_GRID_LEFT_PAD = 3;
    static constexpr uint32_t G_TICTACTOE_GRID_TOP_PAD = 4;

    static constexpr uint32_t G_TICTACTOE_MAXIMUM_ERROR_COUNT = G_TICTACTOE_BOARD_WIDTH * G_TICTACTOE_BOARD_HEIGHT;

    /**
     * @brief Hangman
     */
    static constexpr uint32_t G_HANGMAN_DISPLAY_WIDTH = 62;
    static constexpr uint32_t G_HANGMAN_DISPLAY_HEIGHT = 22;

    static constexpr uint32_t G_HANGMAN_MINIMUM_WORD_LENGTH = 3;
    static constexpr uint32_t G_HANGMAN_MAXIMUM_WORD_LENGTH = 14;
    static constexpr uint32_t G_HANGMAN_MAXIMUM_ERROR_COUNT = 10;
    static constexpr uint32_t G_HANGMAN_KEY_PRESS_CHAR_OFFSET = 32;
    static constexpr uint32_t G_HANGMAN_NUMBER_OF_LETTERS_IN_THE_ALPHABET = 26;

    static constexpr uint32_t G_HANGMAN_USER_INPUT_ROW = 13;
    static constexpr uint32_t G_HANGMAN_GET_WORD_FROM_USER_COLUMN = 39;
    static constexpr uint32_t G_HANGMAN_GET_USER_COMMAND_COLUMN = 41;

    /**
     * @brief Battleships
     */
    static constexpr uint32_t G_BATTLESHIPS_DISPLAY_WIDTH = 147;
    static constexpr uint32_t G_BATTLESHIPS_DISPLAY_HEIGHT = 38;
    static constexpr uint32_t G_BATTLESHIPS_BOARD_WIDTH = 10;
    static constexpr uint32_t G_BATTLESHIPS_BOARD_HEIGHT = 10;
    static constexpr uint32_t G_BATTLESHIPS_GRID_ELEMENT_WIDTH = 4;
    static constexpr uint32_t G_BATTLESHIPS_GRID_ELEMENT_HEIGHT = 2;
    static constexpr uint32_t G_BATTLESHIPS_GRID_LEFT_PAD = 10;
    static constexpr uint32_t G_BATTLESHIPS_GRID_TOP_PAD = 8;

    static constexpr uint32_t G_BATTLESHIPS_SHIP_COUNT = 5;

    static constexpr uint32_t G_BATTLESHIPS_CARRIER_SIZE = 5;
    static constexpr uint32_t G_BATTLESHIPS_BATTLESHIP_SIZE = 4;
    static constexpr uint32_t G_BATTLESHIPS_DESTROYER_SIZE = 3;
    static constexpr uint32_t G_BATTLESHIPS_SUBMARINE_SIZE = 3;
    static constexpr uint32_t G_BATTLESHIPS_PATROL_BOAT_SIZE = 2;

    static const std::string G_BATTLESHIPS_CARRIER_NAME = "Carrie";
    static const std::string G_BATTLESHIPS_BATTLESHIP_NAME = "Battleship";
    static const std::string G_BATTLESHIPS_DESTROYER_NAME = "Destroyer";
    static const std::string G_BATTLESHIPS_SUBMARINE_NAME = "Submarine";
    static const std::string G_BATTLESHIPS_PATROL_BOAT_NAME = "Patrol Boat";

    static const std::string G_BATTLESHIPS_PLACED_SHIP {static_cast<char>(178)};
    static const std::string G_BATTLESHIPS_SUCCESSFUL_ATTACK {static_cast<char>(176)};
    static const std::string G_BATTLESHIPS_MISSED_ATTACK {static_cast<char>(250)};

    static const std::array<std::string, G_BATTLESHIPS_SHIP_COUNT> G_BATTLESHIPS_SHIP_NAMES = {
        G_BATTLESHIPS_CARRIER_NAME,
        G_BATTLESHIPS_BATTLESHIP_NAME,
        G_BATTLESHIPS_DESTROYER_NAME,
        G_BATTLESHIPS_SUBMARINE_NAME,
        G_BATTLESHIPS_PATROL_BOAT_NAME};

    static const std::array<uint32_t, G_BATTLESHIPS_SHIP_COUNT> G_BATTLESHIPS_SHIP_SIZES = {
        G_BATTLESHIPS_CARRIER_SIZE,
        G_BATTLESHIPS_BATTLESHIP_SIZE,
        G_BATTLESHIPS_DESTROYER_SIZE,
        G_BATTLESHIPS_SUBMARINE_SIZE,
        G_BATTLESHIPS_PATROL_BOAT_SIZE};

    static const std::array<std::string, G_BATTLESHIPS_SHIP_COUNT> G_BATTLESHIPS_SHIP_INSTRUCTIONS = {
        TerminalGames::ImplementStdFormat("Please enter the {} grid locations for the Carrier", G_BATTLESHIPS_CARRIER_SIZE),
        TerminalGames::ImplementStdFormat("Please enter the {} grid locations for the Battleship", G_BATTLESHIPS_BATTLESHIP_SIZE),
        TerminalGames::ImplementStdFormat("Please enter the {} grid locations for the Destroyer", G_BATTLESHIPS_DESTROYER_SIZE),
        TerminalGames::ImplementStdFormat("Please enter the {} grid locations for the Submarine", G_BATTLESHIPS_SUBMARINE_SIZE),
        TerminalGames::ImplementStdFormat("Please enter the {} grid locations for the Patrol Boat", G_BATTLESHIPS_PATROL_BOAT_SIZE)};

    /**
     * @brief PageBuilder
     */
    // When highlighting what is currently selected in a menu
    static const std::string G_SELECTOR = ">";

    // Bottom box titles
    static const std::string G_MENU_BOTTOM_TITLE = "q = quit";
    static const std::string G_GAME_BOTTOM_TITLE = "q = quit to main menu";

    // ANSI colour escape codes
    static const std::string G_WHITE_ANSI_COLOUR_ESCAPE_CODE = "\x1B[1;37m";
    static const std::string G_RED_ANSI_COLOUR_ESCAPE_CODE = "\x1B[1;31m";
    static const std::string G_BLUE_ANSI_COLOUR_ESCAPE_CODE = "\x1B[1;34m";
    static const std::string G_RESET_ANSI_COLOUR_ESCAPE_CODE = "\x1B[0m";

    // Extended ASCII characters for edges and corners of the page
    static constexpr char G_HORIZONTAL_LINE = static_cast<char>(205);
    static constexpr char G_VERTICAL_LINE = static_cast<char>(186);
    static constexpr char G_TOP_RIGHT_CORNER = static_cast<char>(187);
    static constexpr char G_BOTTOM_RIGHT_CORNER = static_cast<char>(188);
    static constexpr char G_BOTTOM_LEFT_CORNER = static_cast<char>(200);
    static constexpr char G_TOP_LEFT_CORNER = static_cast<char>(201);

    /**
     * @brief Terminal
     */
    // Keyboard values when getting user input on Windows
    static constexpr uint32_t G_ENTER_KEY = '\r';
    static constexpr uint32_t G_BACKSPACE_KEY = 8;
    static constexpr uint32_t G_UP_ARROW_KEY = 72;
    static constexpr uint32_t G_DOWN_ARROW_KEY = 80;
    static constexpr uint32_t G_LEFT_ARROW_KEY = 75;
    static constexpr uint32_t G_RIGHT_ARROW_KEY = 77;
    static constexpr uint32_t G_QUIT_KEY = 'q';
    // Cursor width while running on windows.
    static constexpr uint32_t G_CURSOR_WIDTH_PERCENTAGE = 100;

    // Keyboard values when getting user input on other platforms
    static constexpr uint32_t G_ALTERNATIVE_ENTER_KEY = 'e';
    static constexpr uint32_t G_ALTERNATIVE_BACKSPACE_KEY = 'z';
    static constexpr uint32_t G_ALTERNATIVE_UP_ARROW_KEY = 'w';
    static constexpr uint32_t G_ALTERNATIVE_DOWN_ARROW_KEY = 's';
    static constexpr uint32_t G_ALTERNATIVE_LEFT_ARROW_KEY = 'a';
    static constexpr uint32_t G_ALTERNATIVE_RIGHT_ARROW_KEY = 'd';
    static constexpr uint32_t G_ALTERNATIVE_QUIT_KEY = 'q';

    /**
     * @brief Hangman word list for the computer
     */
    static constexpr uint32_t G_NUMBER_OF_WORDS = 972;
    inline static const std::array<std::string, G_NUMBER_OF_WORDS> G_HANGMAN_COMPUTER_WORDS = {
        "ABILITY",
        "ABLE",
        "ABOUT",
        "ABOVE",
        "ACCEPT",
        "ACCORDING",
        "ACCOUNT",
        "ACROSS",
        "ACT",
        "ACTION",
        "ACTIVITY",
        "ACTUALLY",
        "ADD",
        "ADDRESS",
        "ADMINISTRATION",
        "ADMIT",
        "ADULT",
        "AFFECT",
        "AFTER",
        "AGAIN",
        "AGAINST",
        "AGE",
        "AGENCY",
        "AGENT",
        "AGO",
        "AGREE",
        "AGREEMENT",
        "AHEAD",
        "AIR",
        "ALL",
        "ALLOW",
        "ALMOST",
        "ALONE",
        "ALONG",
        "ALREADY",
        "ALSO",
        "ALTHOUGH",
        "ALWAYS",
        "AMERICAN",
        "AMONG",
        "AMOUNT",
        "ANALYSIS",
        "AND",
        "ANIMAL",
        "ANOTHER",
        "ANSWER",
        "ANY",
        "ANYONE",
        "ANYTHING",
        "APPEAR",
        "APPLY",
        "APPROACH",
        "AREA",
        "ARGUE",
        "ARM",
        "AROUND",
        "ARRIVE",
        "ART",
        "ARTICLE",
        "ARTIST",
        "ASK",
        "ASSUME",
        "ATTACK",
        "ATTENTION",
        "ATTORNEY",
        "AUDIENCE",
        "AUTHOR",
        "AUTHORITY",
        "AVAILABLE",
        "AVOID",
        "AWAY",
        "BABY",
        "BACK",
        "BAD",
        "BAG",
        "BALL",
        "BANK",
        "BAR",
        "BASE",
        "BEAT",
        "BEAUTIFUL",
        "BECAUSE",
        "BECOME",
        "BED",
        "BEFORE",
        "BEGIN",
        "BEHAVIOUR",
        "BEHIND",
        "BELIEVE",
        "BENEFIT",
        "BEST",
        "BETTER",
        "BETWEEN",
        "BEYOND",
        "BIG",
        "BILL",
        "BILLION",
        "BIT",
        "BLACK",
        "BLOOD",
        "BLUE",
        "BOARD",
        "BODY",
        "BOOK",
        "BORN",
        "BOTH",
        "BOX",
        "BOY",
        "BREAK",
        "BRING",
        "BROTHER",
        "BUDGET",
        "BUILD",
        "BUILDING",
        "BUSINESS",
        "BUT",
        "BUY",
        "CALL",
        "CAMERA",
        "CAMPAIGN",
        "CAN",
        "CANCER",
        "CANDIDATE",
        "CAPITAL",
        "CAR",
        "CARD",
        "CARE",
        "CAREER",
        "CARRY",
        "CASE",
        "CATCH",
        "CAUSE",
        "CELL",
        "CENTER",
        "CENTRAL",
        "CENTURY",
        "CERTAIN",
        "CERTAINLY",
        "CHAIR",
        "CHALLENGE",
        "CHANCE",
        "CHANGE",
        "CHARACTER",
        "CHARGE",
        "CHECK",
        "CHILD",
        "CHOICE",
        "CHOOSE",
        "CHURCH",
        "CITIZEN",
        "CITY",
        "CIVIL",
        "CLAIM",
        "CLASS",
        "CLEAR",
        "CLEARLY",
        "CLOSE",
        "COACH",
        "COLD",
        "COLLECTION",
        "COLLEGE",
        "COLOUR",
        "COME",
        "COMMERCIAL",
        "COMMON",
        "COMMUNITY",
        "COMPANY",
        "COMPARE",
        "COMPUTER",
        "CONCERN",
        "CONDITION",
        "CONFERENCE",
        "CONGRESS",
        "CONSIDER",
        "CONSUMER",
        "CONTAIN",
        "CONTINUE",
        "CONTROL",
        "COST",
        "COULD",
        "COUNTRY",
        "COUPLE",
        "COURSE",
        "COURT",
        "COVER",
        "CREATE",
        "CRIME",
        "CULTURAL",
        "CULTURE",
        "CUP",
        "CURRENT",
        "CUSTOMER",
        "CUT",
        "DARK",
        "DATA",
        "DAUGHTER",
        "DAY",
        "DEAD",
        "DEAL",
        "DEATH",
        "DEBATE",
        "DECADE",
        "DECIDE",
        "DECISION",
        "DEEP",
        "DEFENCE",
        "DEGREE",
        "DEMOCRAT",
        "DEMOCRATIC",
        "DESCRIBE",
        "DESIGN",
        "DESPITE",
        "DETAIL",
        "DETERMINE",
        "DEVELOP",
        "DEVELOPMENT",
        "DIE",
        "DIFFERENCE",
        "DIFFERENT",
        "DIFFICULT",
        "DINNER",
        "DIRECTION",
        "DIRECTOR",
        "DISCOVER",
        "DISCUSS",
        "DISCUSSION",
        "DISEASE",
        "DOCTOR",
        "DOG",
        "DOOR",
        "DOWN",
        "DRAW",
        "DREAM",
        "DRIVE",
        "DROP",
        "DRUG",
        "DURING",
        "EACH",
        "EARLY",
        "EAST",
        "EASY",
        "EAT",
        "ECONOMIC",
        "ECONOMY",
        "EDGE",
        "EDUCATION",
        "EFFECT",
        "EFFORT",
        "EIGHT",
        "EITHER",
        "ELECTION",
        "ELSE",
        "EMPLOYEE",
        "END",
        "ENERGY",
        "ENJOY",
        "ENOUGH",
        "ENTER",
        "ENTIRE",
        "ENVIRONMENT",
        "ENVIRONMENTAL",
        "ESPECIALLY",
        "ESTABLISH",
        "EVEN",
        "EVENING",
        "EVENT",
        "EVER",
        "EVERY",
        "EVERYBODY",
        "EVERYONE",
        "EVERYTHING",
        "EVIDENCE",
        "EXACTLY",
        "EXAMPLE",
        "EXECUTIVE",
        "EXIST",
        "EXPECT",
        "EXPERIENCE",
        "EXPERT",
        "EXPLAIN",
        "EYE",
        "FACE",
        "FACT",
        "FACTOR",
        "FAIL",
        "FALL",
        "FAMILY",
        "FAR",
        "FAST",
        "FATHER",
        "FEAR",
        "FEDERAL",
        "FEEL",
        "FEELING",
        "FEW",
        "FIELD",
        "FIGHT",
        "FIGURE",
        "FILL",
        "FILM",
        "FINAL",
        "FINALLY",
        "FINANCIAL",
        "FIND",
        "FINE",
        "FINGER",
        "FINISH",
        "FIRE",
        "FIRM",
        "FIRST",
        "FISH",
        "FIVE",
        "FLOOR",
        "FLY",
        "FOCUS",
        "FOLLOW",
        "FOOD",
        "FOOT",
        "FOR",
        "FORCE",
        "FOREIGN",
        "FORGET",
        "FORM",
        "FORMER",
        "FORWARD",
        "FOUR",
        "FREE",
        "FRIEND",
        "FROM",
        "FRONT",
        "FULL",
        "FUND",
        "FUTURE",
        "GAME",
        "GARDEN",
        "GAS",
        "GENERAL",
        "GENERATION",
        "GET",
        "GIRL",
        "GIVE",
        "GLASS",
        "GOAL",
        "GOOD",
        "GOVERNMENT",
        "GREAT",
        "GREEN",
        "GROUND",
        "GROUP",
        "GROW",
        "GROWTH",
        "GUESS",
        "GUN",
        "GUY",
        "HAIR",
        "HALF",
        "HAND",
        "HANG",
        "HAPPEN",
        "HAPPY",
        "HARD",
        "HAVE",
        "HEAD",
        "HEALTH",
        "HEAR",
        "HEART",
        "HEAT",
        "HEAVY",
        "HELP",
        "HER",
        "HERE",
        "HERSELF",
        "HIGH",
        "HIM",
        "HIMSELF",
        "HIS",
        "HISTORY",
        "HIT",
        "HOLD",
        "HOME",
        "HOPE",
        "HOSPITAL",
        "HOT",
        "HOTEL",
        "HOUR",
        "HOUSE",
        "HOW",
        "HOWEVER",
        "HUGE",
        "HUMAN",
        "HUNDRED",
        "HUSBAND",
        "IDEA",
        "IDENTIFY",
        "IMAGE",
        "IMAGINE",
        "IMPACT",
        "IMPORTANT",
        "IMPROVE",
        "INCLUDE",
        "INCLUDING",
        "INCREASE",
        "INDEED",
        "INDICATE",
        "INDIVIDUAL",
        "INDUSTRY",
        "INFORMATION",
        "INSIDE",
        "INSTEAD",
        "INSTITUTION",
        "INTEREST",
        "INTERESTING",
        "INTERNATIONAL",
        "INTERVIEW",
        "INTO",
        "INVESTMENT",
        "INVOLVE",
        "ISSUE",
        "ITEM",
        "ITS",
        "ITSELF",
        "JOB",
        "JOIN",
        "JUST",
        "KEEP",
        "KEY",
        "KID",
        "KILL",
        "KIND",
        "KITCHEN",
        "KNOW",
        "KNOWLEDGE",
        "LAND",
        "LANGUAGE",
        "LARGE",
        "LAST",
        "LATE",
        "LATER",
        "LAUGH",
        "LAW",
        "LAWYER",
        "LAY",
        "LEAD",
        "LEADER",
        "LEARN",
        "LEAST",
        "LEAVE",
        "LEFT",
        "LEG",
        "LEGAL",
        "LESS",
        "LET",
        "LETTER",
        "LEVEL",
        "LIE",
        "LIFE",
        "LIGHT",
        "LIKE",
        "LIKELY",
        "LINE",
        "LIST",
        "LISTEN",
        "LITTLE",
        "LIVE",
        "LOCAL",
        "LONG",
        "LOOK",
        "LOSE",
        "LOSS",
        "LOT",
        "LOVE",
        "LOW",
        "MACHINE",
        "MAGAZINE",
        "MAIN",
        "MAINTAIN",
        "MAJOR",
        "MAJORITY",
        "MAKE",
        "MAN",
        "MANAGE",
        "MANAGEMENT",
        "MANAGER",
        "MANY",
        "MARKET",
        "MARRIAGE",
        "MATERIAL",
        "MATTER",
        "MAY",
        "MAYBE",
        "MEAN",
        "MEASURE",
        "MEDIA",
        "MEDICAL",
        "MEET",
        "MEETING",
        "MEMBER",
        "MEMORY",
        "MENTION",
        "MESSAGE",
        "METHOD",
        "MIDDLE",
        "MIGHT",
        "MILITARY",
        "MILLION",
        "MIND",
        "MINUTE",
        "MISS",
        "MISSION",
        "MODEL",
        "MODERN",
        "MOMENT",
        "MONEY",
        "MONTH",
        "MORE",
        "MORNING",
        "MOST",
        "MOTHER",
        "MOUTH",
        "MOVE",
        "MOVEMENT",
        "MOVIE",
        "MRS",
        "MUCH",
        "MUSIC",
        "MUST",
        "MYSELF",
        "NAME",
        "NATION",
        "NATIONAL",
        "NATURAL",
        "NATURE",
        "NEAR",
        "NEARLY",
        "NECESSARY",
        "NEED",
        "NETWORK",
        "NEVER",
        "NEW",
        "NEWS",
        "NEWSPAPER",
        "NEXT",
        "NICE",
        "NIGHT",
        "NONE",
        "NOR",
        "NORTH",
        "NOT",
        "NOTE",
        "NOTHING",
        "NOTICE",
        "NOW",
        "N'T",
        "NUMBER",
        "OCCUR",
        "OFF",
        "OFFER",
        "OFFICE",
        "OFFICER",
        "OFFICIAL",
        "OFTEN",
        "OIL",
        "OLD",
        "ONCE",
        "ONE",
        "ONLY",
        "ONTO",
        "OPEN",
        "OPERATION",
        "OPPORTUNITY",
        "OPTION",
        "ORDER",
        "ORGANIZATION",
        "OTHER",
        "OTHERS",
        "OUR",
        "OUT",
        "OUTSIDE",
        "OVER",
        "OWN",
        "OWNER",
        "PAGE",
        "PAIN",
        "PAINTING",
        "PAPER",
        "PARENT",
        "PART",
        "PARTICIPANT",
        "PARTICULAR",
        "PARTICULARLY",
        "PARTNER",
        "PARTY",
        "PASS",
        "PAST",
        "PATIENT",
        "PATTERN",
        "PAY",
        "PEACE",
        "PEOPLE",
        "PER",
        "PERFORM",
        "PERFORMANCE",
        "PERHAPS",
        "PERIOD",
        "PERSON",
        "PERSONAL",
        "PHONE",
        "PHYSICAL",
        "PICK",
        "PICTURE",
        "PIECE",
        "PLACE",
        "PLAN",
        "PLANT",
        "PLAY",
        "PLAYER",
        "POINT",
        "POLICE",
        "POLICY",
        "POLITICAL",
        "POLITICS",
        "POOR",
        "POPULAR",
        "POPULATION",
        "POSITION",
        "POSITIVE",
        "POSSIBLE",
        "POWER",
        "PRACTICE",
        "PREPARE",
        "PRESENT",
        "PRESIDENT",
        "PRESSURE",
        "PRETTY",
        "PREVENT",
        "PRICE",
        "PRIVATE",
        "PROBABLY",
        "PROBLEM",
        "PROCESS",
        "PRODUCE",
        "PRODUCT",
        "PRODUCTION",
        "PROFESSIONAL",
        "PROFESSOR",
        "PROGRAM",
        "PROJECT",
        "PROPERTY",
        "PROTECT",
        "PROVE",
        "PROVIDE",
        "PUBLIC",
        "PULL",
        "PURPOSE",
        "PUSH",
        "PUT",
        "QUALITY",
        "QUESTION",
        "QUICKLY",
        "QUITE",
        "RACE",
        "RADIO",
        "RAISE",
        "RANGE",
        "RATE",
        "RATHER",
        "REACH",
        "READ",
        "READY",
        "REAL",
        "REALITY",
        "REALIZE",
        "REALLY",
        "REASON",
        "RECEIVE",
        "RECENT",
        "RECENTLY",
        "RECOGNIZE",
        "RECORD",
        "RED",
        "REDUCE",
        "REFLECT",
        "REGION",
        "RELATE",
        "RELATIONSHIP",
        "RELIGIOUS",
        "REMAIN",
        "REMEMBER",
        "REMOVE",
        "REPORT",
        "REPRESENT",
        "REPUBLICAN",
        "REQUIRE",
        "RESEARCH",
        "RESOURCE",
        "RESPOND",
        "RESPONSE",
        "RESPONSIBILITY",
        "REST",
        "RESULT",
        "RETURN",
        "REVEAL",
        "RICH",
        "RIGHT",
        "RISE",
        "RISK",
        "ROAD",
        "ROCK",
        "ROLE",
        "ROOM",
        "RULE",
        "RUN",
        "SAFE",
        "SAME",
        "SAVE",
        "SAY",
        "SCENE",
        "SCHOOL",
        "SCIENCE",
        "SCIENTIST",
        "SCORE",
        "SEA",
        "SEASON",
        "SEAT",
        "SECOND",
        "SECTION",
        "SECURITY",
        "SEE",
        "SEEK",
        "SEEM",
        "SELL",
        "SEND",
        "SENIOR",
        "SENSE",
        "SERIES",
        "SERIOUS",
        "SERVE",
        "SERVICE",
        "SET",
        "SEVEN",
        "SEVERAL",
        "SEX",
        "SEXUAL",
        "SHAKE",
        "SHARE",
        "SHE",
        "SHOOT",
        "SHORT",
        "SHOT",
        "SHOULD",
        "SHOULDER",
        "SHOW",
        "SIDE",
        "SIGN",
        "SIGNIFICANT",
        "SIMILAR",
        "SIMPLE",
        "SIMPLY",
        "SINCE",
        "SING",
        "SINGLE",
        "SISTER",
        "SIT",
        "SITE",
        "SITUATION",
        "SIX",
        "SIZE",
        "SKILL",
        "SKIN",
        "SMALL",
        "SMILE",
        "SOCIAL",
        "SOCIETY",
        "SOLDIER",
        "SOME",
        "SOMEBODY",
        "SOMEONE",
        "SOMETHING",
        "SOMETIMES",
        "SON",
        "SONG",
        "SOON",
        "SORT",
        "SOUND",
        "SOURCE",
        "SOUTH",
        "SOUTHERN",
        "SPACE",
        "SPEAK",
        "SPECIAL",
        "SPECIFIC",
        "SPEECH",
        "SPEND",
        "SPORT",
        "SPRING",
        "STAFF",
        "STAGE",
        "STAND",
        "STANDARD",
        "STAR",
        "START",
        "STATE",
        "STATEMENT",
        "STATION",
        "STAY",
        "STEP",
        "STILL",
        "STOCK",
        "STOP",
        "STORE",
        "STORY",
        "STRATEGY",
        "STREET",
        "STRONG",
        "STRUCTURE",
        "STUDENT",
        "STUDY",
        "STUFF",
        "STYLE",
        "SUBJECT",
        "SUCCESS",
        "SUCCESSFUL",
        "SUCH",
        "SUDDENLY",
        "SUFFER",
        "SUGGEST",
        "SUMMER",
        "SUPPORT",
        "SURE",
        "SURFACE",
        "SYSTEM",
        "TABLE",
        "TAKE",
        "TALK",
        "TASK",
        "TAX",
        "TEACH",
        "TEACHER",
        "TEAM",
        "TECHNOLOGY",
        "TELEVISION",
        "TELL",
        "TEN",
        "TEND",
        "TERM",
        "TEST",
        "THAN",
        "THANK",
        "THAT",
        "THE",
        "THEIR",
        "THEM",
        "THEMSELVES",
        "THEN",
        "THEORY",
        "THERE",
        "THESE",
        "THEY",
        "THING",
        "THINK",
        "THIRD",
        "THIS",
        "THOSE",
        "THOUGH",
        "THOUGHT",
        "THOUSAND",
        "THREAT",
        "THREE",
        "THROUGH",
        "THROUGHOUT",
        "THROW",
        "THUS",
        "TIME",
        "TODAY",
        "TOGETHER",
        "TONIGHT",
        "TOO",
        "TOP",
        "TOTAL",
        "TOUGH",
        "TOWARD",
        "TOWN",
        "TRADE",
        "TRADITIONAL",
        "TRAINING",
        "TRAVEL",
        "TREAT",
        "TREATMENT",
        "TREE",
        "TRIAL",
        "TRIP",
        "TROUBLE",
        "TRUE",
        "TRUTH",
        "TRY",
        "TURN",
        "TWO",
        "TYPE",
        "UNDER",
        "UNDERSTAND",
        "UNIT",
        "UNTIL",
        "UPON",
        "USE",
        "USUALLY",
        "VALUE",
        "VARIOUS",
        "VERY",
        "VICTIM",
        "VIEW",
        "VIOLENCE",
        "VISIT",
        "VOICE",
        "VOTE",
        "WAIT",
        "WALK",
        "WALL",
        "WANT",
        "WAR",
        "WATCH",
        "WATER",
        "WAY",
        "WEAPON",
        "WEAR",
        "WEEK",
        "WEIGHT",
        "WELL",
        "WEST",
        "WESTERN",
        "WHAT",
        "WHATEVER",
        "WHEN",
        "WHERE",
        "WHETHER",
        "WHICH",
        "WHILE",
        "WHITE",
        "WHO",
        "WHOLE",
        "WHOM",
        "WHOSE",
        "WHY",
        "WIDE",
        "WIFE",
        "WILL",
        "WIN",
        "WIND",
        "WINDOW",
        "WISH",
        "WITH",
        "WITHIN",
        "WITHOUT",
        "WOMAN",
        "WONDER",
        "WORD",
        "WORK",
        "WORKER",
        "WORLD",
        "WORRY",
        "WOULD",
        "WRITE",
        "WRITER",
        "WRONG",
        "YARD",
        "YEAH",
        "YEAR",
        "YES",
        "YET",
        "YOU",
        "YOUNG",
        "YOUR",
        "YOURSELF"};
}
