name: Build

on: workflow_call

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        defaults:
            run:
                shell: pwsh

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - uses: ilammy/msvc-dev-cmd@v1
              if: ${{ matrix.os }} == 'windows-latest'

            - name: Build Terminal Games
              run: |
                  Import-Module ./modules/Build.psd1
                  Build-CppCodeUsingCMake -Platform ${{ matrix.os }} -BuildType Release -BuildDirectory build -Parallel 8 -Verbose

            - name: Upload executable as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: terminal-games-${{ matrix.os }}
                  path: ./build/terminal-games*
                  if-no-files-found: error
