name: Continuous Deployment

run-name: CD - ${{ github.run_number }} - ${{ github.ref }}

on:
    push:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: pwsh

        steps:
            - uses: actions/checkout@v4

            - name: Install build dependencies
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Install-BuildDependencies -OperatingSystem "${{ matrix.os }}" -Verbose

            - name: Configure CMake
              run: cmake -S . -B ./build -G "Ninja"

            - name: Build Project
              run: cmake --build ./build --config Release

            - uses: actions/upload-artifact@v4
              with:
                  name: terminal-games-${{ matrix.os }}
                  path: ./build/terminal-games-${{ matrix.os }}*
                  if-no-files-found: error

    release:
        needs: build
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v4

            - uses: actions/download-artifact@v4
              with:
                  pattern: terminal-games-*

            - name: Set release tag name
              run: echo "tag=terminal-games-$(date +%Y-%m-%d)-(${{ github.run_number }})" >> $GITHUB_ENV

            - name: Create new release
              run: gh release create "${{ env.tag }}" ./terminal-games-macos-latest/terminal-games-macos-latest ./terminal-games-ubuntu-latest/terminal-games-ubuntu-latest ./terminal-games-windows-latest/terminal-games-windows-latest.exe --generate-notes --latest
              env:
                  GH_TOKEN: ${{ github.token }}
