name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: pwsh

        steps:
            - uses: actions/checkout@v4

            - name: Install build dependencies
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Install-BuildDependencies -Verbose

            - name: Configure CMake
              run: cmake -S . -B ./build -G "Ninja"

            - name: Build Project
              run: cmake --build ./build --config Release

            - uses: actions/upload-artifact@v4
              with:
                  name: terminal-games-${{ matrix.os }}
                  path: ./build/terminal-games-${{ matrix.os }}*
                  if-no-files-found: error

    lint:
        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: pwsh

        steps:
            - uses: actions/checkout@v4

            - name: Install linting dependencies
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Install-LintingDependencies -Verbose

            - name: Run gitattributes linter
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Test-GitAttributesFile -Verbose

            - name: Run cspell config linter
              if: success() || failure()
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Test-CSpellConfigurationFile -Verbose

            - name: Run cspell
              if: success() || failure()
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Test-CodeUsingCSpell -Verbose

            - name: Run prettier
              if: success() || failure()
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Test-CodeUsingPrettier -Verbose

            - name: Run PSScriptAnalyzer
              if: success() || failure()
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Test-CodeUsingPSScriptAnalyzer -Verbose

            - name: Run clang-tidy and clang-format
              if: success() || failure()
              run: |
                  Import-Module ./modules/Terminal-Games.psd1
                  Test-CodeUsingClang -Verbose
