name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          # - macos-latest
          # - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build ${{github.workspace}}/build --config Release     
