name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os:
                    - macos-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Configure CMake
              run: cmake -S . -B ./build -D "CMAKE_BUILD_TYPE=Release"

            - name: Build Project
              run: cmake --build ./build --config Release

    linting:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dev dependencies
              run: npm install

            - name: Run cspell
              run: npx cspell .

            - name: Run prettier (for JSON linting)
              if: success() || failure()
              run: npx prettier . --check



            - name: Show diff
              run: |
                  npx prettier . --write
                  git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
                  npm install -g diff2html-cli
                  diff2html -i file -s side -F diff.html -- diff.txt

            - name: Upload html diff
              uses: actions/upload-artifact@v4
              with:
                  name: HTML Diff
                  path: diff.html
                  retention-days: 3


            - name: Run PSScriptAnalyzer (for PowerShell linting)
              if: success() || failure()
              shell: pwsh
              run: Invoke-ScriptAnalyzer -Path . -Recurse -Severity Information

            - name: Run gitattributes linter
              if: success() || failure()
              shell: pwsh
              run: |
                  Import-Module ./scripts/Linters.psm1

                  Test-GitAttributesFile -Verbose
