name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        uses: ./.github/workflows/Build.yml

    lint:
        uses: J-Afzal/Linters/.github/workflows/Linting-ps1.yml@main
