name: Continuous Deployment

run-name: CD - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    push:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Configure CMake
              run: cmake -S . -B ./build

            - name: Build Project
              run: cmake --build ./build --config Release

            - uses: actions/upload-artifact@v4
              with:
                name: terminal-games-${{ matrix.os }}
                path: ./build/terminal-games*
                if-no-files-found: error

    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/download-artifact@v4
              with:
                pattern: terminal-games*

            - name: Get current date
              run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV

            - name: test
              run: |
                echo "cd-release-${{ env.date }}-${{ github.run_number }}"
                ls

            # - name: Create new release
            #   run: gh release create "cd-release-${{ env.date }}-${{ github.run_number }}"
