name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os:
                    # - macos-latest
                    # - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Configure CMake
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

            - name: Build Project
              run: cmake --build ${{github.workspace}}/build --config Release

    linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run cspell
              if: success() || failure()
              run: npx cspell@8.17.0 .

            - name: Run markdownlint
              if: success() || failure()
              run: npx markdownlint-cli@0.43.0 .

            - name: Run yamllint
              if: success() || failure()
              run: |
                pip install --user yamllint
                yamllint .
