name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        uses: ./.github/workflows/Build.yml

    lint:
        uses: ./.github/workflows/Linting-ps1.yml
        with:
            path_to_linters_submodule_root: './submodules/Linters'
