name: Continuous Integration

run-name: CI - ${{ github.run_number }} - ${{ github.head_ref }}

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        strategy:
            matrix:
                os:
                    # - macos-latest
                    - ubuntu-latest
                    # - windows-latest

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Install build dependencies
              bash:
              run: |
                  if [ "${{ matrix.os }}" = "macos-latest" ]
                  then
                      brew update
                      brew upgrade

                      brew install ninja
                  fi

                  if [ "${{ matrix.os }}" = "ubuntu-latest" ]
                  then
                      echo "-------------"
                      clang-tidy --version
                      echo "-------------"
                      clang-format --version
                      echo "-------------"

                      sudo apt-get update
                      sudo apt-get upgrade

                      echo "-------------"
                      clang-tidy --version
                      echo "-------------"
                      clang-format --version
                      echo "-------------"

                      sudo apt-get install ninja-build
                      sudo apt-get install clang-tidy clang-format

                      echo "-------------"
                      clang-tidy --version
                      echo "-------------"
                      clang-format --version
                      echo "-------------"
                  fi

            - name: Configure CMake
              run: cmake -S . -B ./build -G "Ninja"

            - name: Run clang-tidy and clang-format
              pwsh:
              run: |
                  Write-Host "-------------"
                  clang-tidy --version
                  Write-Host "-------------"
                  clang-format --version
                  Write-Host "-------------"

                  Import-Module ./scripts/Linters.psm1
                  Test-TerminalGamesCode -Verbose"

            - name: Build Project
              run: cmake --build ./build --config Release

    linting:
        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Install linting dependencies
              run: npm install

            - name: Run cspell
              run: npx cspell .

            - name: Run prettier (for JSON linting)
              if: success() || failure()
              run: npx prettier . --check

            - name: Run PSScriptAnalyzer (for PowerShell linting)
              if: success() || failure()
              shell: pwsh
              run: Invoke-ScriptAnalyzer -Path . -Recurse -Severity Information

            - name: Run gitattributes linter
              if: success() || failure()
              shell: pwsh
              run: |
                  Import-Module ./scripts/Linters.psm1
                  Test-GitAttributesFile -Verbose
