name: Release

on:
    workflow_call:
        inputs:
            ci_check:
                required: false
                type: boolean
                default: false

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
            id-token: write
        defaults:
            run:
                shell: pwsh

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download built artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: terminal-games-*

            - name: Create new release
              run: |
                  $releaseTitle = "Terminal Games $(Get-Date -Format 'yyyy-MM-dd HH-mm-ss')"
                  $tagName = "terminal-games-$(Get-Date -Format 'yyyy-MM-dd-HH-mm-ss')"
                  $sharedName = "terminal-games"

                  # Create draft release if performing a CI check
                  if ($${{ inputs.ci_check }}) {
                    gh release create $tagName `
                        ./$sharedName-macos-latest/$sharedName-macos-latest `
                        ./$sharedName-ubuntu-latest/$sharedName-ubuntu-latest `
                        ./$sharedName-windows-latest/$sharedName-windows-latest.exe `
                        --title $releaseTitle --generate-notes --latest --draft
                  }

                  else {
                    gh release create $tagName `
                        ./$sharedName-macos-latest/$sharedName-macos-latest `
                        ./$sharedName-ubuntu-latest/$sharedName-ubuntu-latest `
                        ./$sharedName-windows-latest/$sharedName-windows-latest.exe `
                        --title $releaseTitle --generate-notes --latest
                  }

              env:
                  GH_TOKEN: ${{ github.token }}

            - name: Upload doxygen documentation artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  name: doxygen-docs
                  path: ./docs/html/

            - name: Release GitHub pages
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: doxygen-docs
                  token: ${{ github.token }}
